// <auto-generated />
using System;
using MediaStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaStore.Migrations
{
    [DbContext(typeof(AimsContext))]
    [Migration("20260309205822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaStore.Data.Book", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("authors");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("coverType");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genre");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language");

                    b.Property<int?>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publicationDate");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("publisher");

                    b.HasKey("MediaId");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.CdAndLp", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<string>("Artists")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("artists");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genre");

                    b.Property<bool>("IsCd")
                        .HasColumnType("bit")
                        .HasColumnName("isCD");

                    b.Property<string>("RecordLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recordLabel");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("releaseDate");

                    b.Property<string>("TrackList")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("trackList");

                    b.HasKey("MediaId");

                    b.ToTable("CD_and_LP", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.DeliveryInfo", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("province");

                    b.HasKey("DeliveryId");

                    b.ToTable("DeliveryInfo", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.Dvd", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("director");

                    b.Property<string>("DvdType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dvdType");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genre");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("language");

                    b.Property<DateOnly?>("ReleasedDate")
                        .HasColumnType("date")
                        .HasColumnName("releasedDate");

                    b.Property<int>("Runtime")
                        .HasColumnType("int")
                        .HasColumnName("runtime");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("studio");

                    b.Property<string>("Subtitles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("subtitles");

                    b.HasKey("MediaId");

                    b.ToTable("DVD", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int")
                        .HasColumnName("totalAmount");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.HasKey("InvoiceId");

                    b.HasIndex(new[] { "OrderId" }, "invoice_order_id_index");

                    b.HasIndex(new[] { "TransactionId" }, "invoice_transaction_id_index");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("imageUrl");

                    b.Property<DateOnly?>("ImportDate")
                        .HasColumnType("date")
                        .HasColumnName("importDate");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<string>("ProductDimension")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productDimension");

                    b.Property<bool?>("RushOrderSupported")
                        .HasColumnType("bit")
                        .HasColumnName("rushOrderSupported");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int")
                        .HasColumnName("totalQuantity");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("MediaId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MediaStore.Data.OrderInfo", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<int>("ShippingFees")
                        .HasColumnType("int")
                        .HasColumnName("shippingFees");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Subtotal")
                        .HasColumnType("int")
                        .HasColumnName("subtotal");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "DeliveryId" }, "delivery_id_index");

                    b.ToTable("OrderInfo", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.OrderMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderType")
                        .HasColumnType("int")
                        .HasColumnName("orderType");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("MediaId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("Order_Media", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("BankTransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bankTransactionId");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cardType");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<int>("PaymentAmount")
                        .HasColumnType("int")
                        .HasColumnName("paymentAmount");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("paymentTime");

                    b.HasKey("TransactionId");

                    b.ToTable("PaymentTransaction", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.RushOrderInfo", b =>
                {
                    b.Property<int>("RushId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rush_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RushId"));

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deliveryTime");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("instruction");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.HasKey("RushId");

                    b.HasIndex(new[] { "OrderId" }, "rush_order_id_index");

                    b.ToTable("RushOrderInfo", (string)null);
                });

            modelBuilder.Entity("MediaStore.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("MediaStore.Data.Book", b =>
                {
                    b.HasOne("MediaStore.Data.Media", "Media")
                        .WithOne("Book")
                        .HasForeignKey("MediaStore.Data.Book", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book__media_id__3B75D760");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaStore.Data.CdAndLp", b =>
                {
                    b.HasOne("MediaStore.Data.Media", "Media")
                        .WithOne("CdAndLp")
                        .HasForeignKey("MediaStore.Data.CdAndLp", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CD_and_LP__media__3E52440B");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaStore.Data.Dvd", b =>
                {
                    b.HasOne("MediaStore.Data.Media", "Media")
                        .WithOne("Dvd")
                        .HasForeignKey("MediaStore.Data.Dvd", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DVD__media_id__412EB0B6");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaStore.Data.Invoice", b =>
                {
                    b.HasOne("MediaStore.Data.OrderInfo", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Invoice__order_i__52593CB8");

                    b.HasOne("MediaStore.Data.PaymentTransaction", "Transaction")
                        .WithMany("Invoices")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoice__transac__5165187F");

                    b.Navigation("Order");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MediaStore.Data.OrderInfo", b =>
                {
                    b.HasOne("MediaStore.Data.DeliveryInfo", "Delivery")
                        .WithMany("OrderInfos")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderInfo__deliv__45F365D3");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("MediaStore.Data.OrderMedia", b =>
                {
                    b.HasOne("MediaStore.Data.Media", "Media")
                        .WithMany("OrderMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Order_Med__media__48CFD27E");

                    b.HasOne("MediaStore.Data.OrderInfo", "Order")
                        .WithMany("OrderMedia")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Order_Med__order__49C3F6B7");

                    b.Navigation("Media");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MediaStore.Data.RushOrderInfo", b =>
                {
                    b.HasOne("MediaStore.Data.OrderInfo", "Order")
                        .WithMany("RushOrderInfos")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RushOrder__order__4CA06362");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MediaStore.Data.DeliveryInfo", b =>
                {
                    b.Navigation("OrderInfos");
                });

            modelBuilder.Entity("MediaStore.Data.Media", b =>
                {
                    b.Navigation("Book");

                    b.Navigation("CdAndLp");

                    b.Navigation("Dvd");

                    b.Navigation("OrderMedia");
                });

            modelBuilder.Entity("MediaStore.Data.OrderInfo", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderMedia");

                    b.Navigation("RushOrderInfos");
                });

            modelBuilder.Entity("MediaStore.Data.PaymentTransaction", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
